### ISSUE TITLE
Adicionar slide "Sobre o GDGJF"

### ISSUE THREAD

**Issue by TiagoGouvea** [gdgjf/apresentacao.gdgjf#3]
- [ ] Adicionar slide "Sobre o GDGJF" 

- O GDGJF foi trazido para Juiz de Fora por Tiago Gouvêa em 2014
- Eventos realizados (até set 2020): 120 
- Foto do hackathon com legenda "1⁰ Hackathon do GDGJF - Julho de 2014"

![DSCN9677](https://user-images.githubusercontent.com/2242549/94344085-4b149f80-fff3-11ea-9ec0-8b58488b4ef0.JPG)

**Comment by ravaiano** [comment]
Pronto.
