### ISSUE TITLE
Adicionar slide "Como participar"

### ISSUE THREAD

**Issue by TiagoGouvea** [gdgjf/apresentacao.gdgjf#4]
- [ ] Adicionar slide "Como participar" - "Basta se inscrever na plataforma do GDG, para ser notificado de todo novo evento"  - "Além de ir aos grupos de estudos e demais eventos, você também pode participar apresentando conteúdos, se tornando um embaixador em sua instituição e até como organizador, basta conversar com os responsáveis em qualquer evento, demonstrar seu interesse e começar efetivamente a apoiar as ações do grupo."

**Comment by ravaiano** [comment]
Pronto !!

**Comment by TiagoGouvea** [comment]
Este código não está no repositório, acho que esqueceu de subir.
